// Automatically generated by MockGen. DO NOT EDIT!
// Source: vendor/code.cloudfoundry.org/buildpackapplifecycle/buildpackrunner/runner.go

package main_test

import (
	buildpackapplifecycle "code.cloudfoundry.org/buildpackapplifecycle"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Runner interface
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *_MockRunnerRecorder
}

// Recorder for MockRunner (not exported)
type _MockRunnerRecorder struct {
	mock *MockRunner
}

func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &_MockRunnerRecorder{mock}
	return mock
}

func (_m *MockRunner) EXPECT() *_MockRunnerRecorder {
	return _m.recorder
}

func (_m *MockRunner) Run(config *buildpackapplifecycle.LifecycleBuilderConfig) error {
	ret := _m.ctrl.Call(_m, "Run", config)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRunnerRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run", arg0)
}
